version: '2.0'
services:
  poshtibansaz:
    image: docker.bale.ai/hackathon/grpc:0.1-1
    container_name: poshtibansaz
    hostname: poshtibansaz
    environment:
      - TOKEN=ca0c0e3ff745f4977f5702743d6b0461d79c9063
      - DB_PATH=rocksdb